import { Container, Typography } from "@mui/material";
import Head from "next/head";
import AnimationWalk from "src/components/shared/Animation";
import Footer from "src/components/shared/BottomNavigationFooter";
import Maps from "../../components/shared/Maps";
import { ListContentProps } from "../interfaces/modules/lista";
import { UserPlaces } from "../interfaces/shared/userPlaces";


const ListContent = ({ place, loading, animation, openAnimation }: ListContentProps) => {

    return (
        <div >
            <Head>
                <title>No rolê - Lista</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {animation ?
                <Container maxWidth='lg' sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', width: '100vw', padding: '2rem' }}>
                    <AnimationWalk />
                    <Typography variant="h4">Carregando...</Typography>
                </Container>
                :
                <>
                    <Container sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', marginLeft: '0.6rem' }}>


                        <>
                            <Typography color="primary" variant="h5"  >Sua lista</Typography>
                            {place ?
                                (!loading && place.map((place: UserPlaces) => {

                                    return (
                                        <Maps therm={place.therm} key={place.title} src={place.src} title={place.title} isAList />

                                    )
                                }))

                                : <Typography variant="body1" >Sua lista está vazia!</Typography>}
                        </>


                    </Container>
                </>
            }

            <Footer openAnimation={openAnimation} />
        </div>
    )
};

export default ListContent;