import { Container, Typography } from "@mui/material";
import Head from "next/head";
import Maps from "../../components/shared/Maps";
import { UserPlaces } from "../interfaces/shared/userPlaces";


const ListContent = ( {place, loading }: any ) => {

    return (
        <div >
            <Head>
                <title>No rolê - Lista</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container sx={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', margin: 'auto' }}>

                <Typography color="primary" variant="h5"  >Sua lista</Typography>
                {place ?
                    (!loading && place.map((place: UserPlaces) => {

                        return (
                            <Maps therm={place.therm} src={place.src} title={place.title} />

                        )
                    }))

                    : <Typography variant="body1" >Sua lista está vazia!</Typography>}

            </Container>
        </div>
    )
};

export default ListContent;