import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>No rolê</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet"/>
      </Head>
      <main className='container'>
            <div className='banner__container'>
                <img className='banner__img' src="https://res.cloudinary.com/twenty20/private_images/t_standard-fit/v1620958105/photosp/b322df1c-219d-49ae-94d3-3a16280cd011/b322df1c-219d-49ae-94d3-3a16280cd011.jpg" alt="" />
            </div>
            <h2 className='title'>Escolha o seu rolê!</h2>
              <ul>
                <li className='item'>marque os lugares que já conheceu</li>
                <li className='item'>marque os lugares que quer conhecer</li>
              </ul>
      </main>
    </div>
  )
}
