import { Button, Container, Typography } from "@mui/material";
import Head from "next/head"
import { useEffect, useState } from "react";
import Maps from "../components/shared/Maps";

const List = () => {
  const [loading, setLoading] = useState(false);
  const [place, setPlace] = useState([]);

  useEffect(()=>{
    setLoading(true)
    const currentPlaces = JSON.parse(localStorage.getItem('USER_PLACES'))
    setPlace(currentPlaces);
  
    setTimeout(()=>{
      setLoading(false)

    },2000 )

  },[])
console.log(place)

    return (
        <div >
        <Head>
          <title>No rolê - Lista</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
           
              <Typography color="secondary"  >Sua lista</Typography>
              {place ? 
            (!loading && place.map((place) => {

              return( 
                        <Maps place={place} key={place.title}/>
                    
                     

              )
          }))
         
              : <p>Sua lista está vazia!</p>}
            
        </Container>
      </div>
    )
}

export default List;