import Head from "next/head"

const About = () => {


    return (
        <div >
        <Head>
          <title>No rolê - Sobre</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className='container column'>
           
              <h2 className='title'>Sobre</h2>
             
        </main>
      </div>
    )
}

export default About;